#!/bin/sh

dbStore=/var/www/territoriolinux/Store/
dbStorage=/var/storage/

rsync -avr --delete /mnt/LV/Github/territoriolinux/Store/ 138.68.78.228:/$dbStore > /tmp/log 2>&1 ;
rsync -avr --delete /mnt/LV/Github/storage/ 138.68.78.228:/$dbStorage >> /tmp/log 2>&1 ;
