#!/bin/sh
# <.> the point is the original command for <source>

## WEBBMS -- Web Blog Main Source
## WEBBMD -- Web Blog Main Destination
## WEBBGS -- Web Blog Game Source
## WEBBGD -- Web Blog Game Destination
## WEBBBS -- Web Blog BarcelonaDo Source
## WEBBBD -- Web Blog BarcelonaDo Destination
WEBBMS=/mnt/LV/Github/tl/Blog/.Md-files/Posted
WEBBMD=/mnt/LV/Github/tl/Blog/.Md-files/
WEBBGS=/mnt/LV/Github/tl/Blog/Games/.MdFiles/Posted
WEBBGD=/mnt/LV/Github/tl/Blog/Games/.MdFiles/
WEBBBS=/mnt/LV/Github/tl/Blog/barcelonaDo/Posted
WEBBBD=/mnt/LV/Github/tl/Blog/barcelonaDo/
####
##GITBMS -- Git Blog Main Source
##GITBMD -- Git Blog Main Destination
##GITBGS -- Git Blog Game Source
##GITBGD -- Git Blog Game Destination
##GITBBS -- Git Blog barcelonaDo Source
##GITBBD -- Git Blog barcelonaDo Destination
GITBMS=/mnt/LV/Github/ts/Blog/.currentWork
GITBMS1=/mnt/LV/Github/ts/Blog/.ready
GITBMS2=/mnt/LV/Github/ts/Blog/.toReview
GITBMS3=/mnt/LV/Github/ts/Blog/Archives
GITBMD=/mnt/LV/Github/ts/Blog/
GITBGS=/mnt/LV/Github/ts/Blog/Games/.currentWork
GITBGS1=/mnt/LV/Github/ts/Blog/Games/.ready
GITBGS2=/mnt/LV/Github/ts/Blog/Games/.toReview
GITBGD=/mnt/LV/Github/ts/Blog/Games/
GITBBS=/mnt/LV/Github/ts/Blog/barcelonaDo/.currentWork
GITBBS1=/mnt/LV/Github/ts/Blog/barcelonaDo/.ready
GITBBS2=/mnt/LV/Github/ts/Blog/barcelonaDo/.toReview
GITBBD=/mnt/LV/Github/ts/Blog/barcelonaDo/
####
## WEBDS -- Web Documentation Source
## WEBDS -- Web Documentation Destination
## WEBDAD -- Web Documentation Articles Destination
WEBDS=/mnt/LV/Github/tl/TerritorioLinux/.Md-files/Posted
WEBDD=/mnt/LV/Github/tl/TerritorioLinux/.Md-files/
WEBDAD=/mnt/LV/Github/tl/TerritorioLinux/.Md-files/
####
## GITDS -- Git Documentation Source
## GITDS -- Git Documentation Destination
## GITDAR -- Git Documentation Repo Source
GITDS=/mnt/LV/Github/ts/Documentacion/Temas
GITDD=/mnt/LV/Github/ts/Documentacion/
GITDAR=/mnt/LV/Github/ts/Documentacion/.currentWork
GITDAR1=/mnt/LV/Github/ts/Documentacion/.ready
GITDAR2=/mnt/LV/Github/ts/Documentacion/.toReview
####
## WEBGS -- Web Games Source
## WEBGD -- Web Games Destination
WEBGS=/mnt/LV/Github/tl/Games/.Md-files/Posted
WEBGD=/mnt/LV/Github/tl/Games/.Md-files/
####
## GITGS -- Git Games Source
## GITGD -- Git Games Destination
GITGEXCLUDE=/mnt/LV/Github/ts/Games/Posted
GITGS=/mnt/LV/Github/ts/Games/
GITGD=/mnt/LV/Github/ts/Games/
####
## 
GITBS=/mnt/LV/Github/ts/barcelonaDo/
GITBD=/mnt/LV/Github/ts/barcelonaDo/
##
WEBBS=/mnt/LV/Github/tl/barcelonaDo/Posted
WEBBD=/mnt/LV/Github/tl/barcelonaDo/

####
HOUSE=/mnt/LV/Github/ts
CTRLOUT=/mnt/LV/Github/ts/Logs/CtrlRepoLogs/ctrl.log

## El enfoque de la aplicacion(rsync), es coger una lista de variables -son todos los archivos y directorios que van a ser sincronizados, extrayendo todas las reglas ejem: includes/excludes/ etc. a archivos externos. Con esto conseguimos simplificar la llamada a la aplicacion, manteniendo reglas complejas, en archivos separados. 
## El enfoque que yo he preparado, es el opuesto; son construidas reglas in "situ" especificas para cada directorio o archivo. Hay mucho que refactorizar aqui, juas.
## IDEA -- coger la lista de variables, y preparar un "FILTER", en el archivo donde se incluye los directorios/archivos a sincronizar, tambien pueden incluirse las "reglas", aunque estas habra que colocarlas al principio del archivo, o de lo contrario no seran alcanzadas cuando deban aplicarse.
## Otra nota, "rsync" proporciona un mecanismo para evitar el borrado de archivos que fueron anteriormente "guardados(backed-up)", esto significa, que la regla "--delete" sobre directorios y archivos guardados con anterioridad, no sera aplicada!!. CONVIENE LEER LA PAGINA DE MANUAL.
## Otra nota, los filtros NO son rutas hacia la "X", es un PATRON de texto -algo asi como un REGEX, que tendra encuenta la aplicacion, sobre el directorio que se le dijo trabajase.
