#!/bin/sh

rsync -avr /home/raul/Github/territoriolinux/barcelonaDo/{.MdFiles,POSTED} \
/home/raul/Github/territoriolinux/TerritorioLinux/.Md-files/Repo/BarcelonaDo/ \
1> /home/raul/Github/The-side-of-the-source/Logs/CtrlRepoLogs/ctrl.log

