#!/bin/sh

source /mnt/LV/Github/the-side-of-the-source-code/Admin_aps/Diferido/gv

##TODO To refactor, all is the same function, and is needed to serialize it.
## It is posible? to construck a block {arg1, arg2} reading it from a 2D Array
## and iterate over, till the end. So write it in C implies to "rewrite the wheel" cause 
##  "rsync" functions are implemented on "C", or "Bash", anyway, the function to do the
## [ -r jobs ], is TRUE.
## The CTRLOUT var, needed to refactor to be only one call, on the begining of de document
##  instead every single job!

rm $CTRLOUT

## Main Blog
rsync -a --delete {$GITBMS,$GITBMS1,$GITBMS2} $WEBBMD > $CTRLOUT 2>&1
rsync -a --delete $WEBBMS $GITBMD >> $CTRLOUT 2>&1
rsync -a --delete $GITBMS3 $WEBBMD >> $CTRLOUT 2>&1
## Blog Games
rsync -a --delete {$GITBGS,$GITBGS1,$GITBGS2} $WEBBGD >> $CTRLOUT 2>&1
rsync -a --delete $WEBBGS $GITBGD >> $CTRLOUT 2>&1
## Blog BarcelonaDo
rsync -a --delete {$GITBBS,$GITBBS1,$GITBBS2}  $WEBBBD >> $CTRLOUT 2>&1
rsync -a --delete $WEBBBD $GITBBD >> $CTRLOUT 2>&1
## Main Pages
rsync -avr --delete $GITDS $WEBDD >> $CTRLOUT 2>&1
rsync -a --delete $WEBDS $GITDD >> $CTRLOUT 2>&1
rsync -a --delete {$GITDAR,$GITDAR1,$GITDAR2} $WEBDAD >> $CTRLOUT 2>&1
## Games Page
rsync -a --delete --exclude='Posted' $GITGS $WEBGD >> $CTRLOUT 2>&1
rsync -a --delete $WEBGS $GITGD >> $CTRLOUT 2>&1
## BarcelonaDo Page
rsync -a --delete --exclude='Posted' $GITBS $WEBBD >> $CTRLOUT 2>&1
rsync -a --delete $WEBBS $GITBD >> $CTRLOUT 2>&1
## User preferences & configuration
if [[ -d $GEDITSS ]]; then
	rsync -a --delete $GEDITSS $GEDITSD >> $CTRLOUT 2>&1
	else
		echo "¿estamos reescribiendo la historia?" > /tmp/WARNING
fi

