DROP FUNCTION IF EXISTS CalculoIVA;
DELIMITER $$
CREATE FUNCTION CalculoIVA
(x DECIMAL(12,4))
RETURNS DECIMAL(12,4) 
DETERMINISTIC 
BEGIN 
  DECLARE IVA DECIMAL(12,4); -- OR FLOAT etc
  SET IVA = x *1.16; 
  RETURN IVA;
END;$$
DELIMITER ;

select CalculoIVA(9.12);
-- 10.5792
